name: spinn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scipy
  - pytorch
  - ipython
  - jupyter
  - compilers
  - pip
  - pip:
      - vtk
      - mayavi
      - automan
